### ISSUE TITLE
Rule is not detected

### ISSUE THREAD

**Issue by sciphy-maker** [ItalikDev/plg_h5p_userpoints#1]
Hi !
thanks a lot ! 
I've installed the plugin in joomla with the classic method, it seems there's no problem, plugin is installed, so I activated it.
However, user points don't detect the new rule when clicking on "autodetect new rule" in userpoints manager.
What I've done wrong ?
Thanks again
Damien

**Comment by ItalikDev** [comment]
Hello!
The rule will be added automatically after the first points are awarded.
You will pass the test and will see the rule and the awarded points

Vitalii

**Comment by sciphy-maker** [comment]
Hello,
thanks,
I did this, but it seems it doesn't work. Points aren't earned.
Moreover, users's results in the h5p component (all h5p contents/results) don't appear any more (only the old ones, not the new).
Can you help me, please ?
Thanks a lot.
Damien

**Comment by ItalikDev** [comment]
And if you disable the plugin, the H5P points are not shown either?

Check parameter "User Results" in Settings it should be turned on.

**Comment by sciphy-maker** [comment]
I've disabled the plugin, new results are showed, but not if the plugin is enable.
User results is turned on

**Comment by ItalikDev** [comment]
Do you have a test user (frontend)? Can you send me his login and password?

**Comment by sciphy-maker** [comment]
yes,
here it is, mail has been sent.
Thanks !

**Comment by ItalikDev** [comment]
Update plugin "Correctly adding a rule to a new UserPoints installation"

https://github.com/ItalikDev/plg_h5p_userpoints/releases/tag/1.0.2

**Comment by sciphy-maker** [comment]
Yes !!! It works !
Great !!!
Thanks a lot !!!
